### ISSUE TITLE
/w/entry.sh: 3: set: Illegal option -o pipefail

### ISSUE THREAD

**Issue by yegor256** [g4s8/xcop-action#2]
I'm getting this error with the current version of the plugin:

```
/w/entry.sh: 3: set: Illegal option -o pipefail
```

For example: https://github.com/jcabi/jcabi-ssh/runs/7701783775?check_suite_focus=true

**Comment by yegor256** [comment]
@g4s8 can you please help?

**Comment by g4s8** [comment]
@yegor256 should be resolved, please check a new version
