### ISSUE TITLE
Error installing xcop inside a Docker container

### ISSUE THREAD

**Issue by volodya-lombrozo** [g4s8/xcop-action#4]
@g4s8 We experience [some problems](https://github.com/objectionary/eo/issues/1682#issuecomment-1382249547) when using `xcop-action` for our pipelines. `xcop-action` just fails during an installation step.
The error message:
```
ERROR:  Error installing xcop:
[81](https://github.com/objectionary/eo/actions/runs/3910262074/jobs/6682255756#step:2:81)
  	The last version of nokogiri (~> 1.10) to support your Ruby & RubyGems was 1.13.10. Try installing it with `gem install nokogiri -v 1.13.10` and then running the current command again
[82](https://github.com/objectionary/eo/actions/runs/3910262074/jobs/6682255756#step:2:82)
  	nokogiri requires Ruby version >= 2.7, < 3.3.dev. The current ruby version is 2.6.10.210.
[83](https://github.com/objectionary/eo/actions/runs/3910262074/jobs/6682255756#step:2:83)
  Successfully installed racc-1.6.2
[84](https://github.com/objectionary/eo/actions/runs/3910262074/jobs/6682255756#step:2:84)
  The command '/bin/sh -c gem install xcop' returned a non-zero code: 1
```
Full log right [here](https://github.com/objectionary/eo/actions/runs/3910262074/jobs/6682255756#step:2:59)

**Comment by g4s8** [comment]
@volodya-lombrozo try using some stable version to avoid docker building in GH actions, e.g. `g4s8/xcop-action@1.0` instead of `g4s8/xcop-action@master`

**Comment by volodya-lombrozo** [comment]
@g4s8 It doesn't work.  Please, have a look on that PR: https://github.com/objectionary/eo/pull/1685
`xcop-action` still fails here (even if we use specific version `1.0`).

**Comment by yegor256** [comment]
@g4s8 @volodya-lombrozo I believe, upgrading to Ruby 3.0 will solve the problem: https://github.com/g4s8/xcop-action/blob/master/Dockerfile#L1
