### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by volodya-lombrozo** [g4s8/xcop-action#6]
@g4s8 I want to set some particular version for our pipelines -`1.0` for example, but it [doesn't work](https://github.com/objectionary/eo/pull/1685).
It works perfectly only with the latest `master` version. Could you release a new stable version, `2.0` for example?

**Comment by g4s8** [comment]
Done, please check `1.1` release.

**Comment by volodya-lombrozo** [comment]
@g4s8 Yes, it works. Thanks
