### ISSUE TITLE
set default path to include *.xsl, *xsd, *.xhtml, and *.xml

### ISSUE THREAD

**Issue by yegor256** [g4s8/xcop-action#9]
Since #3 is solved, it would be great to make the plugin to include other file formats by default, not only `*.xml`.

**Comment by yegor256** [comment]
@maxonfjvipon maybe you can contribute?

**Comment by maxonfjvipon** [comment]
@yegor256 so you want me just to add checking `*.xsl`, `*xsd`, `*.xhtml`, and `*.xml` by default?

**Comment by maxonfjvipon** [comment]
@g4s8 please release a new version
